name: bulk_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.7
  # State management
  flutter_bloc: ^8.1.3
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  # for dependency injection
  get_it: ^7.6.4
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  pretty_dio_logger: ^1.3.1
  # localization
  intl: ^0.19.0
  easy_localization: ^3.0.7
  # for splash screen
  flutter_native_splash: ^2.4.1
  # An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.0.10+1
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.0
  firebase_core: ^3.2.0
  # Flutter library to load and cache network images.
  cached_network_image: ^3.3.1
  # reading and writing simple key-value pairs
  shared_preferences: ^2.2.3
  # provides API to store data in secure storage.
  flutter_secure_storage: ^9.2.2
  # easy way to add shimmer effect
  flutter:
    sdk: flutter
  bloc: ^8.1.4


  injectable: ^2.4.2
  equatable: ^2.0.5
  animate_do: ^3.3.4
  vector_graphics: ^1.1.11+1
  vector_graphics_compiler: ^1.1.11+1
  synchronized: ^3.1.0+1
  lottie: ^3.1.2
  loading_animation_widget: ^1.2.1
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  image: ^4.2.0
  mime: ^1.0.5
  awesome_notifications: ^0.9.3+1
  flutter_local_notifications: ^17.2.1+2
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  image_compress: ^0.0.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4
  path: ^1.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
  - family: Tajawal
    fonts:
      - asset: assets/fonts/Tajawal/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/jsons/
    - assets/translation/en-US.json
    - assets/translation/ar-SA.json
        # Apply transformer to a folder of SVGs
    - path: assets/images/asset 0.svg
      transformers:
        - package: vector_graphics_compiler
